name: Java CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build Docker image
      run: |
        VERSION=$(date +%s)
        docker build . --file Dockerfile --tag docker.pkg.github.com/misaelntirushwa/events-planning-api/api:${VERSION}
        docker login docker.pkg.github.com --username misaelntirushwa --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/misaelntirushwa/events-planning-api/api:${VERSION}
